version: "3"

# Run 'docker compose up' to start all containers

# Default Network
networks:
  app-network:
    driver: bridge

volumes:
  postdata:

services:
  db:
    container_name: docker-database-post-single
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
    - postdata:/var/lib/postgresql/data

  api:
    container_name: api-post
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
      - app-network
    env_file:
      - .env.production
    depends_on:
      - db